# Site settings
title: Proyecto Ciencia de Datos - Grupo 12 - Clustering de usuarios de MyAnimeList

description: 
  Nuestro proyecto se sumerge en el vasto universo de MyAnimeList y Anime-Planet,
  desentrañando las complejidades de las comunidades de amantes del anime para revelar insights
  valiosos sobre sus hábitos, preferencias y dinámicas.

lang: es-MX

baseurl: "/benjamin0jeda.github.io" # the subpath of your site, e.g. /blog/
url: https://benjamin0jeda.github.io # the base hostname & protocol for your site

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: slate # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
# plugins:
#   - jekyll-feed
#   - jekyll-redirect-from
#   - jekyll-seo-tag
#   - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: America/Santiago
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true

